### ISSUE TITLE
beta 5.0 Video Youtube Download Error.

### ISSUE THREAD

**Issue by bonxz** [MediaGrabber/iOS-Workflow#14] opened 2020-09-05 08:52 UTC
![IMG_4910](https://user-images.githubusercontent.com/61289944/92301693-f044d680-ef65-11ea-9a4b-85c097963161.jpeg)

**Comment by sayem314** [comment] 2020-09-08 14:53
This is caused by the youtube rate-limit. Thousands of people use MG everyday and hence this happens a lot. I'm working on a method to decrypt videos locally to avoid this in the future version.

**Comment by sayem314** [comment] 2020-09-11 08:29
Fixed on beta 6

**Closed by sayem314** 2020-09-11 08:29 UTC
